### PR TITLE
init azure pipelines

### PR DESCRIPTION
**Pull request by jamiebuilds**

### CODE REVIEW

**Comment by shirshak55** [comment]
just to question is extern crate still needed?

**Comment by jamiebuilds** [comment]
Imma be real with you, I don't know what the point of extern crate is

**Comment by shirshak55** [comment]
It was used in past for dependencies but with new version of rust I don't think it is necessary .

**Comment by jamiebuilds** [comment]
Oh neat.

What about with macros, I've had to do this a number of times:

```rust
#[macro_use]
extern crate clap;
```

**Comment by shirshak55** [comment]
Docs says 

"Note that you'll still need `#[macro_rules]` to use macros you've defined
in your own crate; this feature only works for importing macros from
external crates."

So I think for your usecase it is optional? Anyway compiling the app will let us know easily 👍

**Pull request merged**
